version: '3'

services:
  redis:
    image: "redis:alpine"
    networks: [main]

  server:
    build: .
    ports:
      - "8000:8000"
    networks: [main]
    environment:
      REDIS_HOST: redis

networks:
  main: