#
# API
#

put:
  path: /values/{key}
  controller: App\Controller\PutValueController
  methods: ["PUT"]

delete:
  path: /values/{key}
  controller: App\Controller\DeleteValueController
  methods: ["DELETE"]

get:
  path: /values/{key}
  controller: App\Controller\GetValueController
  methods: ["GET"]

#
# Public
#
view_values:
  path: /
  controller: App\Controller\ViewValuesController
  methods: GET


view_value:
  path: /{key}
  controller: App\Controller\ViewValueController
  methods: GET